name = "CharDisplay"
uuid = "30bcdc87-1d00-4f18-8b01-f1692152c509"
authors = ["Evgeny Metelkin <metelkin@insysbio.com>"]
version = "0.1.0"

[deps]
BaremetalPi = "3a90a9a9-52f9-452b-94bd-193d585bd84f"
